server:
  port: 9001

spring:
  application:
    name: paycore
  datasource: #定义数据源
    url: jdbc:mysql://localhost:3306/pay?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

dubbo:
  # 扫描包地址
  scan:
    base-packages: easypay.service
  application:
    name: paycore
  # 协议
  protocol:
    name: dubbo
    port: -1  # 采用默认的自增端口
  # 注册地址
  registry:
    address: nacos://localhost:55001/


# 服务版本号
service:
  version: 1.0.0

  ## log
logging:
  config: classpath:logback.xml
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # mapper-locations: classpath:mapper/*Mapper.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    access-token: default_token
    admin-addresses: http://127.0.0.1:8080/xxl-job-admin
    appname: paycore
    log-path: ~/logs/xxl-job/jobhandler/
    log-retention-days: 30
    ip: 127.0.0.1
    port: 9990